name: Build Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Qt 5.15
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          cache: true

      - name: Set up MSVC Build Tools (Windows)
        if: runner.os == 'Windows'
        run: |
          # Install MSVC build tools
          choco install visualstudio2019-workload-vctools
          # Set up environment variables for MSVC
          echo "Setting up Visual Studio environment..."
          C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\VsDevCmd.bat

      - name: Configure project
        run: qmake -r ModelViewer.pro

      - name: Build (Linux/macOS)
        if: runner.os != 'Windows'
        run: make -j$(nproc)

      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: |
          # Ensure MSVC is used for building
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\VsDevCmd.bat"
          nmake  # If using MSVC
