name: Build Project

on:
  push:
    branches:
      - master
  pull_request:

env:
  VCPKG_OVERLAY_PORTS: ${{ github.workspace }}/.github/vcpkg_overlays/qt

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt install          \
          ninja-build


      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install              \
            ninja

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.2'
          cache: 'true'

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11.5
        with:
            vcpkgJsonGlob: vcpkg.json

      - name: Build
        uses: lukka/run-cmake@v10
        with:
            configurePreset: "ninja_release_vcpkg"
            buildPreset: "Ninja Release"
