name: Build Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Qt 5.15
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          cache: true

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libglm-dev libassimp-dev libfreetype6-dev

      - name: Install Windows dependencies via vcpkg
        if: runner.os == 'Windows'
        run: |
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          cd C:\vcpkg
          bootstrap-vcpkg.bat
          .\vcpkg.exe install assimp glm freetype
          .\vcpkg.exe integrate install

      - name: Set up MSVC Build Tools (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          choco install visualstudio2019-workload-vctools --yes

      - name: Configure project
        run: qmake -r ModelViewer.pro

      - name: Build on Linux/macOS
        if: runner.os != 'Windows'
        run: make -j$(nproc)

      - name: Build on Windows
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\VsDevCmd.bat"
          nmake
